// Generated by CoffeeScript 1.6.2
(function() {
  this.MenuCtrl = function($scope) {
    return $scope.navLinks = [
      {
        text: 'Breakfast',
        href: 'Breakfast.html'
      }, {
        text: 'Lunch',
        href: 'Lunch.html'
      }, {
        text: 'Dinner',
        href: 'Dinner.html'
      }
    ];
  };

}).call(this);
