// Generated by CoffeeScript 1.6.2
(function() {
  var copy;

  copy = function(from, to, propertyNames) {
    var propertyName, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = propertyNames.length; _i < _len; _i++) {
      propertyName = propertyNames[_i];
      _results.push(to[propertyName] = from[propertyName]);
    }
    return _results;
  };

  this.Menu = angular.module('Menu', []);

  this.Menu.config(function($routeProvider) {
    return $routeProvider.when('/menu/:meal', {
      templateUrl: 'partials/menu.html',
      controller: 'RouteController'
    }).otherwise({
      redirectTo: '/menu/breakfast'
    });
  });

  this.MenuController = function($scope, $rootScope, $http) {
    $rootScope.navLinks = [
      {
        text: 'Breakfast',
        meal: 'breakfast'
      }, {
        text: 'Lunch',
        meal: 'lunch'
      }, {
        text: 'Dinner',
        meal: 'dinner'
      }
    ];
    $http.get('data/mealMenus.json').success(function(data) {
      return $rootScope.mealMenus = data;
    });
    $rootScope.getMenuFor = function(meal) {
      var menu;

      if (this.mealMenus[meal] != null) {
        return this.mealMenus[meal];
      } else {
        menu = this.mealMenus["default"];
        menu.name = meal;
        return menu;
      }
    };
    return $scope.$on('routeLoaded', function(event, args) {
      $scope.meal = args.meal;
      return $rootScope.meal = args.meal;
    });
  };

  this.RouteController = function($scope, $rootScope, $routeParams) {
    var meal;

    meal = $routeParams.meal;
    $scope.menu = meal;
    meal = $rootScope.getMenuFor(meal);
    return copy(meal, $scope, ['name', 'headings', 'items']);
  };

}).call(this);
